In [22]:
import tensorflow as tf
import numpy as np

In [11]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
    print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [27]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
# Using method 1
print("Using method 1")
for window in dataset:
    print(list(window.as_numpy_iterator()))
# Using method 2
print("Using method 2")
for window in dataset:
    for val in window:
        print(val.numpy(), end = " ")
    print()

Using method 1
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]
Using method 2
0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [40]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window in dataset:
    print(list(window.as_numpy_iterator()))

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]


In [41]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
# flat_map will convert the batches into tensors from _VariantDataset
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [46]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda x: x.batch(5))
# dataset = dataset.map(lambda x: x.batch(5))
dataset = dataset.map(lambda x: (x[:-1], x[-1]))
for (window_x, window_y) in dataset:
    print(window_x.numpy(), end="\t")
    print(window_y.numpy())

[0 1 2 3]	4
[1 2 3 4]	5
[2 3 4 5]	6
[3 4 5 6]	7
[4 5 6 7]	8
[5 6 7 8]	9
